## Actividad 1: Regresión lineal
### Montiel Navarrete Eliuth

In [ ]:
#Bibliotecas
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score

In [61]:
#Obtención de los datos
url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(url, sep="\s+", skiprows=22, header=None)
datos = np.hstack([raw_df.values[::2, :],
raw_df.values[1::2, 1:2]])
objetivo = raw_df.values[1::2, 2]
df = pd.DataFrame(datos)
df.head()

<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_11379/1935323685.py:3: SyntaxWarning: invalid escape sequence '\s'
  raw_df = pd.read_csv(url, sep="\s+", skiprows=22, header=None)


0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

     11  
0  4.98  
1  9.14  
2  4.03  
3  2.94  
4  5.33

<h3>Regresión lineal</h3>

In [62]:
#Separación de los datos en conjuntos de entrenamiento y de prueba.
xEntrenamiento, xPrueba, yEntrenamiento, yPrueba = train_test_split(df,objetivo,test_size=0.2, random_state=42)

#Separación de los datos en el conjunto de validación.
xEntrenamiento, xValidacion, yEntrenamiento, yValidacion = train_test_split(xEntrenamiento,yEntrenamiento,test_size=0.15,random_state=42)

#Creación del modelo de regrsión lineal.
modelo = LinearRegression()
modelo.fit(xEntrenamiento, yEntrenamiento)
modelo.coef_

array([-1.26191305e-01,  3.48557248e-02,  3.67322608e-02,  3.03423407e+00,
       -1.91636112e+01,  4.85710622e+00, -3.21750411e-04, -1.45280320e+00,
        2.00464727e-01, -9.99639200e-03, -9.01725223e-01, -4.89459119e-01])

In [63]:
#Prueba con los datos de validación.
modelo.predict(xValidacion)

array([22.36266124, 20.82635995, 20.63408845, 23.12046995,  5.60684676,
       28.33224374, 30.85494563, 34.43564423, 20.91018774, 17.75525899,
       27.19520131,  7.31043136, 27.99425231, 17.54738127, 19.52725294,
       22.44261118, 10.04541555, 18.3237474 , 21.20277131, 20.46403564,
       21.27428737, 17.04018834, 28.51840303, 20.26463987, 21.12776917,
       18.35941154, 19.3548454 , 20.59322506, 19.45438498, 13.71812437,
       31.43513611, 24.046919  ,  9.85147781, 36.03848082, 41.26095761,
       35.53894073, 28.9718329 , 28.25486014, 34.95108976, 17.1029386 ,
       17.98811649, 30.89491576, 28.61760981, 28.43867843, 33.0918538 ,
       17.38437692, 34.21245181, 28.36326075, 18.11772814, 20.89309724,
        1.18128852, 25.01202683, 21.71698749, 13.60694187, 11.27401853,
       19.12302379, 20.50119779, 21.46645596, 28.35740811, 34.88132096,
        5.4280692 ])

In [64]:
#Comprobación con los datos reales.
yValidacion

array([21. , 20.4, 19.2, 16.1,  8.5, 24.4, 32.7, 31. , 23.3, 16. , 22.3,
       11.8, 25. , 22.6, 13.3, 17.8,  6.3, 19.1, 27.5, 18.8, 25. , 19.5,
       36.2, 21.7, 20.2, 19.5, 13.4, 18.3, 24.3, 13.9, 28.7, 26.2, 12. ,
       33.3, 46. , 33.4, 33.4, 24.1, 33.1, 14.9, 16.6, 37. , 24.6, 26.4,
       36.1, 19.6, 37.9, 31.2, 20.6, 50. ,  8.8, 25.3, 21.7, 14.5, 23.7,
       20.4, 20.4, 23.2, 22.5, 35.1,  5. ])

In [65]:
yPrediccion = modelo.predict(xValidacion)
rmse = root_mean_squared_error(yValidacion, yPrediccion)
print(f"RMSE: {rmse}")
r2 = r2_score(yValidacion, yPrediccion)
print(f"R2: {r2}")

RMSE: 5.343933721105781
R2: 0.6439021949122865
